const { expect } = require("chai");
const { ethers } = require("hardhat");

describe("FileMetadataRegistry Smart Contract - Phase 5 Test Suite", function () {
  let registry;
  let owner;
  let user1;
  let user2;

  const validFileId = 1;
  const validOwnerId = "101";
  const validCid = "QmXoypizjW3WknFiJnKLwHCnL72vedxjQkDDP1mXWo6uco";
  const validSha256 = "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824";

  beforeEach(async function () {
    [owner, user1, user2] = await ethers.getSigners();
    const FileMetadataRegistry = await ethers.getContractFactory("FileMetadataRegistry");
    registry = await FileMetadataRegistry.deploy();
    await registry.waitForDeployment();
  });

  // ---------------------------------------------------------------------------
  // TEST A — Contract Deployment
  // ---------------------------------------------------------------------------
  it("TEST A — Smart contract deploys successfully with valid contract address and owner", async function () {
    const address = await registry.getAddress();
    expect(address).to.be.a("string").and.not.empty;
    expect(await registry.owner()).to.equal(owner.address);
  });

  // ---------------------------------------------------------------------------
  // TEST B — Initial State Verification
  // ---------------------------------------------------------------------------
  it("TEST B — Unregistered file ID returns false and reverts on getFile", async function () {
    const unregisteredId = 9999;
    expect(await registry.isFileRegistered(unregisteredId)).to.be.false;
    await expect(registry.getFile(unregisteredId)).to.be.revertedWith("File record not found");
  });

  // ---------------------------------------------------------------------------
  // TEST C — Register File Metadata Record
  // ---------------------------------------------------------------------------
  it("TEST C — Registering valid file record succeeds and updates count", async function () {
    await expect(registry.registerFile(validFileId, validOwnerId, validCid, validSha256))
      .to.not.be.reverted;

    expect(await registry.isFileRegistered(validFileId)).to.be.true;
    expect(await registry.getRegisteredFileCount()).to.equal(1);
  });

  // ---------------------------------------------------------------------------
  // TEST D — Retrieve File Metadata Record
  // ---------------------------------------------------------------------------
  it("TEST D — getFile returns accurate immutable metadata fields", async function () {
    await registry.registerFile(validFileId, validOwnerId, validCid, validSha256);

    const record = await registry.getFile(validFileId);
    expect(record.recordFileId).to.equal(validFileId);
    expect(record.ownerId).to.equal(validOwnerId);
    expect(record.ipfsCid).to.equal(validCid);
    expect(record.sha256Hash).to.equal(validSha256);
    expect(record.active).to.be.true;
    expect(record.timestamp).to.be.gt(0);
  });

  // ---------------------------------------------------------------------------
  // TEST E — Blockchain Timestamp Generation
  // ---------------------------------------------------------------------------
  it("TEST E — Timestamp is automatically generated by blockchain (block.timestamp > 0)", async function () {
    await registry.registerFile(validFileId, validOwnerId, validCid, validSha256);

    const record = await registry.getFile(validFileId);
    const latestBlock = await ethers.provider.getBlock("latest");
    expect(record.timestamp).to.equal(latestBlock.timestamp);
  });

  // ---------------------------------------------------------------------------
  // TEST F — Duplicate File Registration Prevention
  // ---------------------------------------------------------------------------
  it("TEST F — Registering duplicate file ID reverts", async function () {
    await registry.registerFile(validFileId, validOwnerId, validCid, validSha256);

    await expect(
      registry.registerFile(validFileId, "999", "QmDifferentCID", validSha256)
    ).to.be.revertedWith("Duplicate registration: file ID already registered");
  });

  // ---------------------------------------------------------------------------
  // TEST G — Empty CID Rejection
  // ---------------------------------------------------------------------------
  it("TEST G — Attempting registration with empty CID reverts", async function () {
    await expect(
      registry.registerFile(validFileId, validOwnerId, "", validSha256)
    ).to.be.revertedWith("Invalid IPFS CID: cannot be empty");
  });

  // ---------------------------------------------------------------------------
  // TEST H — Invalid SHA-256 Hash Rejection
  // ---------------------------------------------------------------------------
  it("TEST H — Attempting registration with invalid SHA-256 hash length reverts", async function () {
    // Empty hash
    await expect(
      registry.registerFile(validFileId, validOwnerId, validCid, "")
    ).to.be.revertedWith("Invalid SHA-256 hash: must be exactly 64 hex characters");

    // Invalid length hash (e.g. 32 characters)
    await expect(
      registry.registerFile(validFileId, validOwnerId, validCid, "12345678901234567890123456789012")
    ).to.be.revertedWith("Invalid SHA-256 hash: must be exactly 64 hex characters");
  });

  // ---------------------------------------------------------------------------
  // TEST I — Immutability Requirements
  // ---------------------------------------------------------------------------
  it("TEST I — Original registration metadata fields remain immutable", async function () {
    await registry.registerFile(validFileId, validOwnerId, validCid, validSha256);
    const initialRecord = await registry.getFile(validFileId);

    // Verify contract has no setter/update functions for CID/Hash/Owner
    expect(registry.updateCid).to.be.undefined;
    expect(registry.updateHash).to.be.undefined;
    expect(registry.updateOwner).to.be.undefined;

    const currentRecord = await registry.getFile(validFileId);
    expect(currentRecord.ipfsCid).to.equal(initialRecord.ipfsCid);
    expect(currentRecord.sha256Hash).to.equal(initialRecord.sha256Hash);
    expect(currentRecord.ownerId).to.equal(initialRecord.ownerId);
  });

  // ---------------------------------------------------------------------------
  // TEST J — File Deactivation
  // ---------------------------------------------------------------------------
  it("TEST J — Deactivating file sets active = false while preserving historical metadata", async function () {
    await registry.registerFile(validFileId, validOwnerId, validCid, validSha256);

    await registry.deactivateFile(validFileId);

    const record = await registry.getFile(validFileId);
    expect(record.active).to.be.false;
    // Historical metadata must remain readable
    expect(record.ipfsCid).to.equal(validCid);
    expect(record.sha256Hash).to.equal(validSha256);
    expect(record.ownerId).to.equal(validOwnerId);
  });

  // ---------------------------------------------------------------------------
  // TEST K — Deactivating Already Inactive File Reverts
  // ---------------------------------------------------------------------------
  it("TEST K — Attempting to deactivate an already inactive file reverts", async function () {
    await registry.registerFile(validFileId, validOwnerId, validCid, validSha256);
    await registry.deactivateFile(validFileId);

    await expect(
      registry.deactivateFile(validFileId)
    ).to.be.revertedWith("File record is already inactive");
  });

  // ---------------------------------------------------------------------------
  // TEST L — Unauthorized Deactivation Revert
  // ---------------------------------------------------------------------------
  it("TEST L — Non-owner account cannot deactivate file records", async function () {
    await registry.registerFile(validFileId, validOwnerId, validCid, validSha256);

    await expect(
      registry.connect(user1).deactivateFile(validFileId)
    ).to.be.reverted;
  });

  // ---------------------------------------------------------------------------
  // TEST M — Event Emission Verification
  // ---------------------------------------------------------------------------
  it("TEST M — Emits FileRegistered and FileDeactivated events with correct parameters", async function () {
    // Check FileRegistered event
    await expect(registry.registerFile(validFileId, validOwnerId, validCid, validSha256))
      .to.emit(registry, "FileRegistered")
      .withArgs(validFileId, validOwnerId, validCid, validSha256, (await ethers.provider.getBlock("latest")).timestamp + 1);

    // Check FileDeactivated event
    await expect(registry.deactivateFile(validFileId))
      .to.emit(registry, "FileDeactivated")
      .withArgs(validFileId, (await ethers.provider.getBlock("latest")).timestamp + 1);
  });

  // ---------------------------------------------------------------------------
  // TEST N — Multiple File Registrations Independence
  // ---------------------------------------------------------------------------
  it("TEST N — Registers multiple distinct file records independently", async function () {
    const file1 = { id: 10, owner: "usr_A", cid: "QmCID11111111111111111111111111111111111111111", hash: "1".repeat(64) };
    const file2 = { id: 20, owner: "usr_B", cid: "QmCID22222222222222222222222222222222222222222", hash: "2".repeat(64) };
    const file3 = { id: 30, owner: "usr_C", cid: "QmCID33333333333333333333333333333333333333333", hash: "3".repeat(64) };

    await registry.registerFile(file1.id, file1.owner, file1.cid, file1.hash);
    await registry.registerFile(file2.id, file2.owner, file2.cid, file2.hash);
    await registry.registerFile(file3.id, file3.owner, file3.cid, file3.hash);

    expect(await registry.getRegisteredFileCount()).to.equal(3);

    const rec1 = await registry.getFile(file1.id);
    const rec2 = await registry.getFile(file2.id);
    const rec3 = await registry.getFile(file3.id);

    expect(rec1.ipfsCid).to.equal(file1.cid);
    expect(rec2.ipfsCid).to.equal(file2.cid);
    expect(rec3.ipfsCid).to.equal(file3.cid);
  });
});
